### ISSUE TITLE
ImportError: cannot import name 'TopologicalError' from 'shapely.geos'

### ISSUE THREAD

**Issue by BjGoCraft** [alexandrediasldev/Montreal-Snow#1]
When trying to execute the script with "python3 demo.py --city Kremlin-Bicetre --country France" as stated in the documentation, I get the error "ImportError: cannot import name 'TopologicalError' from 'shapely.geos' (/home/username/.local/lib/python3.10/site-packages/shapely/geos.py)".
There were no errors when installing the requirements.txt.
I'm very new to Python so I can't fix it myself. Is this a problem with the code or did I maybe do anything wrong?
Would love to use this project, it looks really promising :)

**Comment by alexandrediasldev** [comment]
Hello, I may be a little bit late but I updated the project and the requirements and it seems to work fine with the new versions in the requirements
If you are new to python try to use a virtual environment before installing the project and it should work fine (https://docs.python.org/3/library/venv.html)
python -m venv venv
source ./venv/bin/activate
pip install -r requirements.txt
python3 demo.py --city Kremlin-Bicetre --country France
